[package]
name = "tracing-test-macros"
version = "0.1.0"
edition = "2024"
authors = ["Clément Aver <clement.aver@yahoo.fr>"]
categories = ["development-tools::testing"]
description = "Test macros automating tracing subscriber initialization."
keywords = ["tokio", "test", "tracing", "tracing-subscriber"]
license = "MIT"
repository = "https://github.com/ClementAver/tracing-test-macros.git"
include = [
    "Cargo.toml", "src", "tests", "LICENSE", "README.md"
]

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1.0"
default-features = false
features = []

[dependencies.quote]
version = "1.0"
default-features = false
features = []

[dependencies.syn]
version = "2.0"
default-features = false
features = ["proc-macro"]

[dependencies.tokio]
version = "1.52"
default-features = false
features = ["macros", "rt", "rt-multi-thread"]

[dev-dependencies.tracing]
version = "0.1"
default-features = false
features = ["std"]

[dev-dependencies.tracing-subscriber]
version = "0.3"
default-features = true
features = ["env-filter"]

[dev-dependencies.tokio]
version = "1.52"
default-features = true
features = ["full"]